"""empty message

Revision ID: 74adcf5d23bd
Revises: 34ee487d5b0b
Create Date: 2020-12-18 18:05:42.656054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74adcf5d23bd'
down_revision = '34ee487d5b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
