"""empty message

Revision ID: 77c2c371b146
Revises: 989dd9670908
Create Date: 2020-12-27 12:51:05.052728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c2c371b146'
down_revision = '989dd9670908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_details', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('show_details', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('show_details', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('show_details_venue_id_fkey', 'show_details', type_='foreignkey')
    op.create_foreign_key(None, 'show_details', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show_details', type_='foreignkey')
    op.create_foreign_key('show_details_venue_id_fkey', 'show_details', 'venue', ['venue_id'], ['id'])
    op.alter_column('show_details', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('show_details', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('show_details', 'id')
    # ### end Alembic commands ###
